// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// groupLasso
NumericMatrix groupLasso(NumericMatrix X, NumericMatrix Y, double lambda, int T, int n, int p);
RcppExport SEXP _SA24204162_groupLasso(SEXP XSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP TSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(groupLasso(X, Y, lambda, T, n, p));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_sampler
NumericMatrix gibbs_sampler(int n, double a, double b, int num_samples, int burn_in);
RcppExport SEXP _SA24204162_gibbs_sampler(SEXP nSEXP, SEXP aSEXP, SEXP bSEXP, SEXP num_samplesSEXP, SEXP burn_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sampler(n, a, b, num_samples, burn_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204162_groupLasso", (DL_FUNC) &_SA24204162_groupLasso, 6},
    {"_SA24204162_gibbs_sampler", (DL_FUNC) &_SA24204162_gibbs_sampler, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204162(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
