# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Group Lasso Optimization Algorithm
#' 
#' @description This function implements the Group Lasso optimization algorithm to learn coefficients for a multi-task 
#' regression problem. It uses gradient descent with L1 regularization on each group of coefficients (each task).
#' The optimization minimizes the residual sum of squares subject to the group lasso penalty.
#'
#' @param X A numeric matrix of size \code{n * p * T}, where \code{n} is the number of samples, 
#'        \code{p} is the number of features, and \code{T} is the number of tasks.
#' @param Y A numeric matrix of size \code{n * T}, where \code{n} is the number of samples and 
#'        \code{T} is the number of tasks. Each column represents the response for a particular task.
#' @param lambda A regularization parameter that controls the strength of the group lasso penalty.
#' @param T The number of tasks. This defines the number of columns in the output \code{beta} matrix.
#' @param n The number of samples.
#' @param p The number of features in the input matrix.
#' 
#' @return A numeric matrix \code{beta} of size \code{p * T} containing the estimated coefficients for each task.
#'         Each column represents the estimated coefficients for a particular task, and each row corresponds 
#'         to the coefficients of a specific feature.
#'
#' @examples
#' \dontrun{
#'     // Example usage:
#'     beta_hat <- groupLasso(X = X_data, Y = Y_data, lambda = 0.1, T = 5, n = 100, p = 20)
#'     // beta_hat will contain the optimized coefficients for each task
#' }
#' 
#' @export
groupLasso <- function(X, Y, lambda, T, n, p) {
    .Call(`_SA24204162_groupLasso`, X, Y, lambda, T, n, p)
}

#' @title Gibbs sampling algorithm for sampling from the joint distribution of 
#' two variables x and y. 
#' @description The function performs sampling from the conditionaldistributions p(x | y) and p(y | x) iteratively.
#' @param n Integer. The total number of trials for the binomial distribution in each step.
#' @param a Double. The first shape parameter for the Beta distribution.
#' @param b Double. The second shape parameter for the Beta distribution.
#' @param num_samples Integer. The number of posterior samples to draw after burn-in.
#' @param burn_in Integer. The number of initial iterations to discard as burn-in.
#' @return NumericMatrix A matrix of size (num_samples, 2), where each row contains
#' the sampled values of x and y.
#' @examples
#' \dontrun{
#' samples <- gibbs_sampler(10, 2, 2, 1000, 200)
#' }
#' @export
gibbs_sampler <- function(n, a, b, num_samples, burn_in) {
    .Call(`_SA24204162_gibbs_sampler`, n, a, b, num_samples, burn_in)
}

